name: Bug report
description: Report a reproducible bug in Hypergraphx
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide a minimal reproducible example.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the bug?
      placeholder: A concise description of the issue.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact steps and a minimal code snippet.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: input
    id: hgx_version
    attributes:
      label: Hypergraphx version
      placeholder: e.g. 1.7.9
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Python version
      placeholder: e.g. 3.11.8
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, install method, and any relevant dependency versions.
    validations:
      required: false
